language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install -r requirements.txt

# command to run tests
script:
  - nosetests --with-coverage # or py.test for Python versions 3.5 and below

after_success:
- codecov