language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to run tests
script:
  - nosetests --with-coverage # or py.test for Python versions 3.5 and below

after_success:
- codecov